version: '3.1'
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: on-failure
    volumes:
      - /home/mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mapskills
      MYSQL_USER: mapskills
      MYSQL_PASS: mapskills