-- admin-global-students-progress-view.sql 1.2.0 29/04/2017
-- Copyright (c) 2017, Fatec-Jessen Vidal. All rights reserved.
-- Fatec-Jessen Vidal proprietary/confidential. Use is subject to license terms.

DROP VIEW IF EXISTS ADMIN_GLOBAL_STUDENTS_PROGRESS_VIEW;

CREATE VIEW ADMIN_GLOBAL_STUDENTS_PROGRESS_VIEW AS
	SELECT
		UUID_SHORT() AS ID,
		S0.START_YEAR AS START_YEAR,
		S0.START_SEMESTER AS START_SEMESTER,
		I.LEVEL AS LEVEL,
		(SELECT COUNT(S1.ID) FROM STUDENT S1
			INNER JOIN INSTITUTION I1 ON S1.INSTITUTION_CODE = I1.CODE
			WHERE S1.COMPLETED = 0
			AND S1.START_YEAR = S0.START_YEAR
			AND S1.START_SEMESTER = S0.START_SEMESTER
			AND I.LEVEL = I1.LEVEL
			) AS NOT_FINALIZED,
		(SELECT COUNT(S2.ID) FROM STUDENT S2
			INNER JOIN INSTITUTION I2 ON S2.INSTITUTION_CODE = I2.CODE
			WHERE S2.COMPLETED = 1
			AND S2.START_YEAR = S0.START_YEAR
			AND S2.START_SEMESTER = S0.START_SEMESTER
			AND I.LEVEL = I2.LEVEL
			) AS FINALIZED,
		COUNT(S0.ID) TOTAL
	FROM STUDENT S0
	INNER JOIN INSTITUTION I ON S0.INSTITUTION_CODE = I.CODE
	GROUP BY START_YEAR, START_SEMESTER, LEVEL;