INSERT INTO MAPSKILLS.QUESTION (ID, ID_SKILL) VALUES (2, 2);

INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (5, 'Em novos cantores.', 4, 2);
INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (6, 'Em novas composições.', 5, 2);
INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (7, 'Em uma nova estrutura acústica.', 7, 2);
INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (8, 'Em parceirias de mídia.', 3, 2);

INSERT INTO MAPSKILLS.SCENE (ID, _INDEX, TEXT, IMAGE_NAME, ID_GAME_THEME, ID_QUESTION) VALUES (4, 3, 'Precisamos investir em algo.', '5_3_img.jpg', 5, null);
INSERT INTO MAPSKILLS.SCENE (ID, _INDEX, TEXT, IMAGE_NAME, ID_GAME_THEME, ID_QUESTION) VALUES (5, 4, 'Em que iremos investir?', '5_4_img.jpg', 5, 2);
INSERT INTO MAPSKILLS.SCENE (ID, _INDEX, TEXT, IMAGE_NAME, ID_GAME_THEME, ID_QUESTION) VALUES (6, 5, 'Muito bem, iremos providenciar isto já!', '5_5_img.jpg', 5, null);