INSERT INTO MAPSKILLS.SKILL (ID, NAME, DESCRIPTION) VALUES (1, 'Comunicação', 'Avalia a capacidade de expressão pessoal por meio da intelectualidade');
INSERT INTO MAPSKILLS.SKILL (ID, NAME, DESCRIPTION) VALUES (2, 'Liderança', 'Avalia a capacidade de tomada de decisão');

INSERT INTO MAPSKILLS.QUESTION (ID, ID_SKILL) VALUES (1, 1);

INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (1, 'Alternativa A', 5, 1);
INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (2, 'Alternativa B', 3, 1);
INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (3, 'Alternativa C', 8, 1);
INSERT INTO MAPSKILLS.ALTERNATIVE (ID, DESCRIPTION, SKILL_VALUE, ID_QUESTION) VALUES (4, 'Alternativa D', 1, 1);

INSERT INTO MAPSKILLS.SCENE (ID, _INDEX, TEXT, IMAGE_NAME, ID_GAME_THEME, ID_QUESTION) VALUES (1, 0, 'Olá bem vindo', '5_0_img.jpg', 5, null);
INSERT INTO MAPSKILLS.SCENE (ID, _INDEX, TEXT, IMAGE_NAME, ID_GAME_THEME, ID_QUESTION) VALUES (2, 1, 'Agora me responda', '5_1_img.jpg', 5, 1);
INSERT INTO MAPSKILLS.SCENE (ID, _INDEX, TEXT, IMAGE_NAME, ID_GAME_THEME, ID_QUESTION) VALUES (3, 2, 'Humm.. Interessante.', '5_2_img.jpg', 5, null);