INSERT INTO MAPSKILLS.INSTITUTION (CODE, CNPJ, COMPANY, CITY, LEVEL, ID_GAME_THEME) VALUES ('123', '04973674000123', 'Fatec de teste', 'São José', 1, null);

INSERT INTO MAPSKILLS.LOGIN (ID, USERNAME, PASSWORD) VALUES (2, 'mentor@fatec.sp.gov.br', '$2a$05$rxtH5C1Ffra4RgC11DcCK.38QBgbLZdcn0fJO.1V1id5vm.7atCrG');
INSERT INTO MAPSKILLS.MENTOR (NAME, ID_INSTITUTION, ID_LOGIN) VALUES ('Mentor Fatec', 1, 2);