-- admin-level-students-progress-view.sql 1.2.0 29/04/2017
-- Copyright (c) 2017, Fatec-Jessen Vidal. All rights reserved.
-- Fatec-Jessen Vidal proprietary/confidential. Use is subject to license terms.

DROP VIEW IF EXISTS ADMIN_LEVEL_STUDENTS_PROGRESS_VIEW;

CREATE VIEW ADMIN_LEVEL_STUDENTS_PROGRESS_VIEW AS
	SELECT
    CONCAT(S0.START_YEAR, S0.START_SEMESTER) AS YEAR_SEMESTER,
	I.CODE AS CODE,
	I.LEVEL AS LEVEL,
	I.COMPANY AS COMPANY,
		(SELECT COUNT(S1.ID) FROM STUDENT S1
			WHERE S1.COMPLETED = 0
	        AND CONCAT(S1.START_YEAR, S1.START_SEMESTER) = YEAR_SEMESTER
			AND S1.INSTITUTION_CODE = I.CODE
			) AS NOT_FINALIZED,
		(SELECT COUNT(S2.ID) FROM STUDENT S2
			WHERE S2.COMPLETED = 1
			AND CONCAT(S2.START_YEAR, S2.START_SEMESTER) = YEAR_SEMESTER
			AND S2.INSTITUTION_CODE = I.CODE
			) AS FINALIZED,
		COUNT(S0.ID) AS TOTAL
	FROM STUDENT S0
	INNER JOIN INSTITUTION I ON S0.INSTITUTION_CODE = I.CODE
	GROUP BY YEAR_SEMESTER, CODE, LEVEL, COMPANY;
	