-- csv-report-view.sql 1.2.0 29/04/2017
-- Copyright (c) 2017, Fatec-Jessen Vidal. All rights reserved.
-- Fatec-Jessen Vidal proprietary/confidential. Use is subject to license terms.

DROP VIEW IF EXISTS CSV_REPORT_VIEW;

CREATE VIEW CSV_REPORT_VIEW AS
	SELECT	S.ID AS STUDENT_ID,
    		S.RA AS STUDENT_RA,
    		USER.NAME AS STUDENT_NAME,
    		C.CODE AS COURSE_CODE,
    		C.NAME AS COURSE_NAME,
    		I.CODE AS INSTITUTION_CODE,
    		I.COMPANY AS INSTITUTION_COMPANY,
    		I.LEVEL AS INSTITUTION_LEVEL,
    		CONCAT(S.START_YEAR, '/', S.START_SEMESTER) AS YEAR_SEMESTER
	FROM USER
	INNER JOIN STUDENT S ON USER.ID = S.ID_USER
	INNER JOIN COURSE C ON S.ID_COURSE = C.ID
	INNER JOIN INSTITUTION I ON C.ID_INSTITUTION = I.ID
	WHERE S.COMPLETED = TRUE
	ORDER BY YEAR_SEMESTER DESC, STUDENT_RA;