-- institution-students-progress-view.sql 1.2.0 29/04/2017
-- Copyright (c) 2017, Fatec-Jessen Vidal. All rights reserved.
-- Fatec-Jessen Vidal proprietary/confidential. Use is subject to license terms.

DROP VIEW IF EXISTS INSTITUTION_STUDENTS_PROGRESS_VIEW;

CREATE VIEW INSTITUTION_STUDENTS_PROGRESS_VIEW AS
	SELECT
		S0.START_YEAR,
        S0.START_SEMESTER,
		I.CODE AS INSTITUTION_CODE,
		I.LEVEL AS INSTITUTION_LEVEL,
		C.CODE AS COURSE_CODE,
		C.NAME AS COURSE_NAME,
		(SELECT COUNT(S1.ID) FROM STUDENT S1
			WHERE S1.COMPLETED = 0
	        AND S1.INSTITUTION_CODE = I.CODE
	        AND S1.COURSE_CODE = C.CODE
	        AND S1.START_YEAR = START_YEAR
            AND S1.START_SEMESTER = START_SEMESTER
	        ) AS NOT_FINALIZED,
		(SELECT COUNT(S2.ID) FROM STUDENT S2
			WHERE S2.COMPLETED = 1
	        AND S2.INSTITUTION_CODE = I.CODE
	        AND S2.COURSE_CODE = C.CODE
	        AND S2.START_YEAR = START_YEAR
            AND S2.START_SEMESTER = START_SEMESTER
	        ) AS FINALIZED
	FROM STUDENT S0
	INNER JOIN COURSE C ON S0.ID_COURSE = C.ID
	INNER JOIN INSTITUTION I ON C.ID_INSTITUTION = I.ID
	GROUP BY START_YEAR, START_SEMESTER, INSTITUTION_CODE, INSTITUTION_LEVEL, COURSE_CODE, COURSE_NAME;